### ISSUE TITLE
save relative image urls but ouput absolute ones

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/API#150]
**Describe the bug**

The domain (plus port if non standard) should be NOT saved to the database as otherwise we have the same situation like wordpress where you have to migrate data to work between local, staging and production or just different domains.
```http://localhost:3030/uploads/avatar_69799620-9ff5-11e8-918a-ed36ffba61fe.jpeg```

**To Reproduce**
go to ```http://localhost:3030/users``` and see absolute paths.

**Expected behavior**
Save the url as a relative path and attach the domain by using an after hook
```/uploads/avatar_69799620-9ff5-11e8-918a-ed36ffba61fe.jpeg```

but output as:
```http://localhost:3030/uploads/avatar_69799620-9ff5-11e8-918a-ed36ffba61fe.jpeg```

**Comment by mbomfim33** [comment]
@appinteractive can I assign this?

**Comment by roschaefer** [comment]
@MarcoBomfim we're not maintaining this repo anymore unless it's something critical like security fixes etc. All repos of the new technology stack are prefixed `Nitro-`, e.g [Nitro-Web](https://github.com/Human-Connection/Nitro-Web) [Nitro-Backend](https://github.com/Human-Connection/Nitro-Backend) [Nitro-Deployment](https://github.com/Human-Connection/Nitro-Deployment) [Nitro-Documentation](https://github.com/Human-Connection/Nitro-Documentation)
