### ISSUE TITLE
[Discussion] Lean Startup

### ISSUE THREAD

**Issue by SebastianStehle** [Human-Connection/API#4]
Hi,

it is probably not the right channel for discussions, but I have a question or a point to make. I follow human-connection since I watched the interview at KenFM and was also thinking about joining the team. What stopped me is the long time you worked on this project. Since 2012 you are working on human-connection in one form or another and you have not released something to the public audience yet. I would name myself an entrepreneur and have co-founded several startups already. Some of them successfully and some not. But what I experienced all he times is that your assumptions from the beginning are usually wrong. Therefore you have to release fast and get out to the public, even with a bad version.

I see 2 challenges in human-connection:

1. How to get a lot of users
2. How to manage the discussions so that you have friendly, fact-oriented and in in general good discussions.

And I think you can only prove them when you go out, you cannot prove your assumptions with a small audience. Perhaps you want to test some of the mechanisms from Stackoverflow to make users to moderators automatically or you other ideas? Get them out and test them. The same with scalability. You already mentioned it somewhere that you think about this problem. But having scalability issues is actually nice, because it means that you have a lot of users. And whatever you do now, will probably not be suitable for 100 times more users tomorrow anyway, so why trying it? Get your MVP out and let us test it.

Sorry, I don't get it. I think the idea to start with a "perfect" version is "stupid".

**Comment by appinteractive** [comment]
Hi Sebastian, thanks for your message. We at Human Connection went through lot of changes as a team in the last 12 months alone. Before that there was a lot of work done in terms of shaping the Idea, and a lot of other stuff. HC is not a typical Startup, it is/was a vibrand (and changing) set of people tryping to get an idea out to the wild. 

And yes, its took to long to get to the point where we are now and a lot of stuff happened in the last couple of months, we:

- had sevaral Crowdfunding Campaigns with over ~3,5k paricipants
- rewrite of the whole codebase
- moved to modern technologies for scalibility
- prepared features and internal testing
- opened the Source Code here on GitHub
- creating and moving our Continious Integration Pipeline from Bamboo to Travis-CI
- we had to replace/modernize a lot of our internal infrastructure 
- switchted on all of our services to Let`s Encypt
- got a decent Email Provider where not half of the mails land into spam folders
- and a lot of other stuff that would took to long but will be maybe done at a later point
There is always more going on underneath then it is visible on the surface.

In the next few days we will invite random donators (all of them will be invited in blocks for skaling) into our already running Alpha-Version of the network which is available in german and english. Its not Perfect but it is a good begining and I'm totaly on your side that we have to test and break stuff to learn from it. 

You can see our current [Roadmap](https://human-connection.org/roadmap/) on our Website.
So thing are getting rolling, and I think we are on a really got way.

Here are same (in fact) small impressions of the current network.

![hc-alpha-impressions](https://user-images.githubusercontent.com/432828/36345120-7e87b2f6-1425-11e8-8739-6df53ebe732a.png)

**Comment by SebastianStehle** [comment]
I think you misunderstand me. I do not say, that you are not working hard or nothing happens. All the screenshots and mockups I have seen are fantastic and the videos make the impressions that you have been thinking about the functionality a lot. But what HC has in common with a startup is that you have a lot of assumptions and what I think it will also have a in common with a startup is that many or most assumptions are wrong. I would be surprised if this would be not the case, because this is kind of normal.

There are startups, e.g. when you build a rocket, where you have to  research a lot. But in the internet business you can just make an ugly prototype and go out to the public with it. Switching to LetsEncrypt? Nice, but you solve it within 5 minutes by just going to cloudflare (I know, no end to end encryption). Scalability? Sure, why not, but you will not start with hundred thousand of active users and servers are cheaper than your time.

There is a very high risk that the first version will fail. This is what the numbers say, because 80% of the startups always fail, so I am afraid that you are wasting your time to build a "perfect" failure. Its better to fail faster so you can try it again more often. Disclaimer: 50% of my startups failed as well.

**Comment by HC-Team** [comment]
I'm totaly on your side, don`t be afraid of making mistakes I agree, that's what happening right now. Some stuff you have still to figure out at a early stage, becaus later in the process it can be 100x times more complex then in the beginning. 

By the way, just switching to CloudFlare does not save you from setting up decent certificates on your side as CF als states in their documentation. And we did that not only for the alpha but for other systems that we are using internally in the company.

Scalability:? By not using redundant systems we had some not so nice enounters with our hosters that lead to several downtimes and also do mean more time investing in server maintenance. If you would invest in decent infrastrucure you can save a lot of time and frustration.

Its always a question of balance between fast and stable. 

And with that project here, it dosen't matter if we as a company fail, the project and the code will still be there.
