### ISSUE TITLE
[BUG] NODE_ENV=test does not change configuration

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/API#60]
According to the [docs](https://docs.feathersjs.com/api/configuration.html), changing `NODE_ENV=test` should load `config/test.json`. But it's loading only `config/local.json`.

Steps to reproduce:
```json
// config/test.json
{
  "seeder": {
    "runOnInit": false,
    "dropDatabase": false
  },
}
```
```json
// config/local.json
{
  "seeder": {
    "runOnInit": true,
    "dropDatabase": false
  },
}
```
Open chromium, visit [chrome://inspect](chrome://inspect/), open dedicated DevTools for Node, then run 
```NODE_ENV=test node --inspect server/index.js```
 from your terminal.

Result of `app.get('seeder').runOnInit` is `true`.

I found out, we're using an outdated version of featherjs. Will we migrate to v3 any time soon? Out of curiosity, I updated `@feathersjs/feathers` and `@feathersjs/configuration` and the new dependencies have the desired behaviour, ie. overwrite the default config with `NODE_ENV.json` config.

**Comment by appinteractive** [comment]
Yeah we want to upgrade after the following branches merge. Then we have a bit more headroom.

**Comment by appinteractive** [comment]
Issue was caused by not using `cross-env` for setting env variables and also by using `process.env.NODE_ENV` without the `.env.` part.
