### ISSUE TITLE
Update Feather to 3.x

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/API#77]
We need to Upgrade Feather to Version 3.x

> Keep in mind that we have to upgrade to the new Channel based Pub/Sub.

- [x] make sure to secure the new channels
- [x] fix failing tests (@visualjerk)

**Comment by visualjerk** [comment]
The tests were working as expected, however we had an issue in the associatedCanDos hook. This issue is fixed now.

**Comment by appinteractive** [comment]
done and on develop. after testing on staging it will be deployed to the alpha after merging to master
