### ISSUE TITLE
Inconsisent test configuration of .travis.yml and package.json

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/API#79]
For debugging and consistency it would be great if Travis could run the same commands which a developer would run on a local machine.

Right now, the `.travis.yml` has a custom run script: https://github.com/Human-Connection/API/blob/develop/.travis.yml#L28, compared to package.json: https://github.com/Human-Connection/API/blob/develop/package.json#L51

**Comment by roschaefer** [comment]
@appinteractive fixed?

**Comment by appinteractive** [comment]
Yes
Am 28. Juni 2018, 22:18 +0200 schrieb Robert Schäfer <notifications@github.com>:
